apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: localhost:5000/nginx
        ports:
        - containerPort: 8080
        env:
          - name: HELLO_USER
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: username
          - name: HELLO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: password
